export const currencyNameList = {
  "AFN": "Afghan Afghani",
  "ALL": "Albanian Lek",
  "AOA": "Angolan Kwanza",
  "XCD": "East Caribbean Dollar",
  "ARS": "Argentine Peso",
  "AMD": "Armenian Dram",
  "AUD": "Australian Dollar",
  "EUR": "Euro",
  "AZN": "Azerbaijani Manat",
  "BSD": "Bahamian Dollar",
  "BHD": "Bahraini Dinar",
  "BDT": "Bangladeshi Taka",
  "BBD": "Barbadian Dollar",
  "BYN": "Belarusian Ruble",
  "BZD": "Belize Dollar",
  "XOF": "West African CFA Franc",
  "BTN": "Bhutanese Ngultrum",
  "BOB": "Bolivian Boliviano",
  "BAM": "Bosnia-Herzegovina Convertible Mark",
  "BWP": "Botswana Pula",
  "BRL": "Brazilian Real",
  "BND": "Brunei Dollar",
  "BGN": "Bulgarian Lev",
  "BIF": "Burundian Franc",
  "KHR": "Cambodian Riel",
  "CAD": "Canadian Dollar",
  "CVE": "Cape Verdean Escudo",
  "CLP": "Chilean Peso",
  "CNY": "Chinese Yuan",
  "COP": "Colombian Peso",
  "KMF": "Comorian Franc",
  "CRC": "Costa Rican Colón",
  "HRK": "Croatian Kuna",
  "CUP": "Cuban Peso",
  "CZK": "Czech Koruna",
  "DKK": "Danish Krone",
  "DJF": "Djiboutian Franc",
  "DOP": "Dominican Peso",
  "EGP": "Egyptian Pound" ,
  "EEK": "Estonian Kroon",
  "ETB": "Ethiopian Birr",
  "FJD": "Fijian Dollar",
  "XAF": "Central African CFA Franc",
  "GMD": "Gambian Dalasi",
  "GEL": "Georgian Lari",
  "GHS": "Ghanaian Cedi",
  "GTQ": "Guatemalan Quetzal",
  "GYD": "Guyanese Dollar",
  "HNL": "Honduran Lempira",
  "HKD": "Hong Kong Dollar",
  "HUF": "Hungarian Forint",
  "ISK": "Icelandic Króna",
  "INR": "Indian Rupee",
  "IDR": "Indonesian Rupiah",
  "IRR": "Iranian Rial",
  "IQD": "Iraqi Dinar",
  "ILS": "Israeli New Shekel",
  "JMD": "Jamaican Dollar",
  "JPY": "Japanese Yen",
  "JOD": "Jordanian Dinar",
  "KZT": "Kazakhstani Tenge",
  "KES": "Kenyan Shilling",
  "KWD": "Kuwaiti Dinar",
  "KGS": "Kyrgyzstani Som",
  "LAK": "Lao Kip",
  "LVL": "Latvian Lats",
  "LBP": "Lebanese Pound",
  "LSL": "Lesotho Loti",
  "LRD": "Liberian Dollar",
  "LYD": "Libyan Dinar",
  "LTL": "Lithuanian Litas",
  "MGA": "Malagasy Ariary",
  "MWK": "Malawian Kwacha",
  "MYR": "Malaysian Ringgit",
  "MVR": "Maldivian Rufiyaa",
  "MTL": "Maltese Lira",
  "MRO": "Mauritanian Ouguiya",
  "MUR": "Mauritian Rupee",
  "MXN": "Mexican Peso",
  "MDL": "Moldovan Leu",
  "MNT": "Mongolian Tögrög",
  "MAD": "Moroccan Dirham",
  "MZN": "Mozambican Metical",
  "MMK": "Myanmar Kyat",
  "NAD": "Namibian Dollar",
  "NPR": "Nepalese Rupee",
  "NZD": "New Zealand Dollar",
  "NIO": "Nicaraguan Córdoba",
  "NGN": "Nigerian Naira",
  "NOK": "Norwegian Krone",
  "OMR": "Omani Rial",
  "PKR": "Pakistani Rupee",
  "PAB": "Panamanian Balboa",
  "PGK": "Papua New Guinean Kina",
  "PYG": "Paraguayan Guaraní",
  "PEN": "Peruvian Sol",
  "PHP": "Philippine Peso",
  "PLN": "Polish Zloty",
  "QAR": "Qatari Riyal",
  "RON": "Romanian Leu",
  "RUB": "Russian Ruble",
  "RWF": "Rwandan Franc",
  "SAR": "Saudi Riyal",
  "RSD": "Serbian Dinar",
  "SCR": "Seychellois Rupee",
  "SGD": "Singapore Dollar",
  "SKK": "Slovak Koruna",
  "SBD": "Solomon Islands Dollar",
  "SOS": "Somali Shilling",
  "ZAR": "South African Rand",
  "KRW": "South Korean Won",
  "LKR": "Sri Lankan Rupee",
  "SDG": "Sudanese Pound",
  "SRD": "Surinamese Dollar",
  "SZL": "Swazi Lilangeni",
  "SEK": "Swedish Krona",
  "CHF": "Swiss Franc",
  "SYP": "Syrian Pound",
  "TWD": "New Taiwan Dollar",
  "TJS": "Tajikistani Somoni",
  "TZS": "Tanzanian Shilling",
  "THB": "Thai Baht",
  "TTD": "Trinidad and Tobago Dollar",
  "TND": "Tunisian Dinar",
  "TRY": "Turkish Lira",
  "TMT": "Turkmenistani Manat",
  "UGX": "Ugandan Shilling",
  "UAH": "Ukrainian Hryvnia",
  "AED": "United Arab Emirates Dirham",
  "GBP": "British Pound Sterling",
  "USD": "United States Dollar",
  "UYU": "Uruguayan Peso",
  "UZS": "Uzbekistani Som",
  "VUV": "Vanuatu Vatu",
  "VEF": "Venezuelan Bolívar",
  "VND": "Vietnamese Dong",
  "YER": "Yemeni Rial",
  "ZMW": "Zambian Kwacha",
  "ZWL": "Zimbabwean Dollar"
}